const initialState = {
  user: {},
  playing: {},
  myList: [],
  trends: [
    {
      title: 'In the Dark',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/99118E/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 164,
      contentRating: 'PG',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },

    {
      title: 'Instinct',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/302140/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 137,
      contentRating: 'PG',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },

    {
      title: 'Grand Hotel',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/5472FF/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 163,
      contentRating: 'PG',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },

    {
      title: 'Final Space',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/CCC539/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 124,
      contentRating: 'PG',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },

    {
      title: 'The InBetween',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/FF7A90/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 179,
      contentRating: 'PG',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
  ],
  originals: [
    {
      _id: '5ea2f32a27431ddedc539325',
      title: 'Stargate Atlantis',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/306880/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 148,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
    {
      _id: '5ea2f37627431ddedc539326',
      title: 'Alien Highway',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/604180/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 128,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
    {
      _id: '5ea2f3c927431ddedc539327',
      title: 'Elementary',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/FF91BA/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 146,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
    {
      _id: '5ea2f43227431ddedc539328',
      title: 'Strange Angel',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/45807C/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 146,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
    {
      _id: '5ea2f49127431ddedc539329',
      title: 'Private Eyes',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/577380/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 146,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
    {
      _id: '5ea2f4cc27431ddedc53932a',
      title: 'NCIS: Los Angeles',
      year: 2019,
      cover: 'http://dummyimage.com/800x600.png/5472FF/ffffff',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      duration: 146,
      contentRating: 'G',
      source: 'https://mdstrm.com/video/58333e214ad055d208427db5.mp4',
      tags: [
        'Action|Adventure',
        'Action|Adventure|Thriller',
        'Horror|Western',
        'Horror|Thriller',
        'Comedy|Romance|Sci-Fi',
        'Adventure|Animation|Children|Comedy|Fantasy',
        'Drama',
      ],
    },
  ],
};

export default initialState;
